/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-08-31 20:49:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.swing.JOptionPane;
import datos.UsuarioDAO;
import domain.Usuarios;
import java.util.ArrayList;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("domain.Usuarios");
    _jspx_imports_classes.add("datos.UsuarioDAO");
    _jspx_imports_classes.add("javax.swing.JOptionPane");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"normalize.css\">\n");
      out.write("    <link rel=\"icon\" href=\"img/LOGO-02.ico\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"stiley-dist.css\">\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=KoHo:wght@300&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <title>Sanco</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");

    HttpSession obju=request.getSession();
    String estado= (String) obju.getAttribute("estado");
    if(estado!=null && !estado.equals("Activo")){
        
      out.write("\n");
      out.write("        <script>alert(\"Estado Inactivo dirigete a una oficina de Sanco\");</script>\n");
      out.write("    ");

        }
    
      out.write("\n");
      out.write("    <header class=\"header\">\n");
      out.write("        <div class=\"header__logo\">\n");
      out.write("            <a href=\"\">\n");
      out.write("                <div class=\"logo__header\">\n");
      out.write("                </div>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <nav class=\"header__nav\">\n");
      out.write("            <a href=\"#inicio\">Inicio</a>\n");
      out.write("            <a href=\"#conocenos\">Conocenos</a>\n");
      out.write("            <a href=\"#Productos\">Productos</a>\n");
      out.write("            <a href=\"#servicios\">Servicios</a>\n");
      out.write("            <a href=\"#ingreso\">Ingreso</a>\n");
      out.write("        </nav>\n");
      out.write("\n");
      out.write("    </header>\n");
      out.write("    <section class=\"container\" id=\"inicio\">\n");
      out.write("        <section class=\"contenedor\">\n");
      out.write("            <div class=\"contenedor__text\">\n");
      out.write("                <h4>\n");
      out.write("                    Más que un banco, somos <span>SANCO</span>, su banco. \n");
      out.write("                </h4>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("        <section class=\"contenedor2\" id=\"conocenos\">\n");
      out.write("            <div class=\"texto__contenedor2\">\n");
      out.write("\n");
      out.write("                <h2>Sanco</h2>\n");
      out.write("                <p>\n");
      out.write("                    Un Banco líder en Colombia para el mercado de empresas, personas y el sector social.<br><br>\n");
      out.write("                    El mejor apoyo para el crecimiento y progreso del Pais.<br><br>\n");
      out.write("                    Un Banco que cumple con los objetivos de liderazgo en eficiencia, \n");
      out.write("                    rentabilidad, utilidad y generación de valor que esperan los accionistas.\n");
      out.write("                </p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"imagen__contenedor2\">\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("        <section class=\"contenedorr\" id=\"Productos\">\n");
      out.write("            <section class=\"productos\">\n");
      out.write("                <div class=\"producto\">\n");
      out.write("                    <div class=\"creditos\">\n");
      out.write("                        <h5>Crédito Libranza</h5>\n");
      out.write("                        <p>\n");
      out.write("                            La empresa descuenta la cuota de la nómina. \n");
      out.write("                            Así de fácil, rápido y seguro es llegar a eso que \n");
      out.write("                            tanto sueñas\n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"creditos\">\n");
      out.write("                        <h5>Crediágil</h5>\n");
      out.write("                        <p>\n");
      out.write("                            Un cupo rotativo para lo que quieras. Ten siempre dinero \n");
      out.write("                            para viajar, remodelar la casa, estudiar y realizar compras. \n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"creditos\">\n");
      out.write("                        <h5>Crédito para moto de bajo cilindraje</h5>\n");
      out.write("                        <p>\n");
      out.write("                            ¡Estrena tu moto más rápido de lo que crees! Conoce la financiación \n");
      out.write("                            más adecuada para ti \n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"creditos\">\n");
      out.write("                        <h5>Crédito a la mano</h5>\n");
      out.write("                        <p>\n");
      out.write("                            Un crédito que entregamos al instante, simple, seguro e inmediato. \n");
      out.write("                            El desembale, un poco de dinero para cubrir un gasto de más.\n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("                <div class=\"producto\">\n");
      out.write("                    <div class=\"cuentas\">\n");
      out.write("                        <h5>Sanco a la Mano</h5>\n");
      out.write("                        <p>\n");
      out.write("                            Una cuenta de ahorros que puedes abrir y manejar desde tu celular \n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"cuentas\">\n");
      out.write("                        <h5>Cuenta de Nómina</h5>\n");
      out.write("                        <p>\n");
      out.write("                            Recibe el pago de la nómina en tu cuenta. Ábrela \n");
      out.write("                            desde internet y recibe la tarjeta débito a domicilio\n");
      out.write("                             sin costo.  \n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"cuentas\">\n");
      out.write("                        <h5>Cuenta Pensión</h5>\n");
      out.write("                        <p>\n");
      out.write("                            Recibe el pago de la pensión en tu cuenta, sin salir de casa, cómodo y seguro. \n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"product\">\n");
      out.write("                    <div class=\"productosim\">\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("        </section>\n");
      out.write("        <section class=\"contenedor3\" id=\"servicios\">\n");
      out.write("            <div class=\"Servicios\">\n");
      out.write("                <a href=\"Ayudas/vistapreguntas.html\">\n");
      out.write("                    <div class=\"cuadro prin\">\n");
      out.write("                        <h4>Preguntas Frecuentes</h4>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("                <a href=\"Ayudas/vistacondinero.html\">\n");
      out.write("                    <div class=\"cuadro seg\">                  \n");
      out.write("                        <h4>Como manejar tu dinero</h4>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("                <a href=\"Ayudas/vistainver.html\">\n");
      out.write("                    <div class=\"cuadro ter\">\n");
      out.write("                        <h4>Las mejores inversiones</h4>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("                <a href=\"Ayudas/vistaseguridad.html\">\n");
      out.write("                    <div class=\"cuadro cua\">\n");
      out.write("                        <h4>Aprende sobre seguridad</h4>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("        <section class=\"contenedor4\" id=\"ingreso\">\n");
      out.write(" \n");
      out.write("            <div class=\"form__contenedor4\">\n");
      out.write("                <form autocomplete=\"off\" action=\"/Bancoapp/ServletLog\" method=\"post\" class=\"formlogin\">\n");
      out.write("                    <h3>Login</h3>\n");
      out.write("                    <label for=\"usuario\">User</label>\n");
      out.write("                    <input type=\"text\" id=\"usu\" name=\"usu\" required>\n");
      out.write("                    <label for=\"password\">Password</label>\n");
      out.write("                    <input type=\"password\" id=\"password\" name=\"password\" required>\n");
      out.write("                    <input type=\"submit\" name=\"btn\" class=\"btn\" value=\"Ingresar\">\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("    </section>\n");
      out.write("    <footer class=\"footer\">\n");
      out.write("        <div class=\"derechos\">\n");
      out.write("            <p class=\"name__footer\">© 2021 Sanco. Todos los derechos reservados. Sanco es una marca registrada.</p>\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
